webdict/appone/urls.py
from django.conf.urls import url,include
from appone import views

app_name = 'appone'

urlpatterns = [
    url(r'^dict/$', views.FormView, name="FormView")
]

webdict/webdict/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from appone import views



urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$',views.index,name='index'),
    url(r'^',include('appone.urls'))

]

webdict/appone/models.py
from django.db import models
import datetime

# Create your models here.
class DictWord(models.Model):
    name = models.CharField(max_length=100,unique=True)
    description = models.TextField(max_length=200)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return str(self.name)

webdict/appone/forms.py
from django import forms
from appone.models import DictWord

class FirstForm(forms.ModelForm):
    class Meta:
        model = DictWord
        #fields = "__all__"
        fields = ('name','description')

class SecondForm(forms.ModelForm):
    class Meta:
        model = DictWord
        #fields = "__all__"
        fields = ('name',)

webdict/appone/views.py
from django.shortcuts import render
from appone.models import DictWord
from appone.forms import FirstForm, SecondForm
from django.contrib import messages



# Create your views here.

def index(request):
    #create form
    form = SecondForm()

    query_list = DictWord.objects.all()
    dict_DictWord = {'words': query_list,"form":form}
    if request.method == "POST":
        form = SecondForm(request.POST)
        if form.is_valid():
            ##delete object from data base
            data = str(form.cleaned_data['name'])
            #naim = request.POST.get('name')
            print(data)
            try:
                DictWord.objects.filter(name=data).delete()
               # model_instance = DictWord.objects.get(name=naim)
               # model_instance.delete()
            except:
                print("duude")
            print("OK")
            return render(request, 'appone/index.html', context = dict_DictWord)
        else:
            messages.error(request, "Error")

    return render(request,'appone/index.html',context=dict_DictWord)


def FormView(request):
    form = FirstForm()
    if request.method == "POST":
        form = FirstForm(request.POST)
        if form.is_valid():
            ##save the form into db
            form.save(commit=True)
            # after submit on users page we redirect the user to index page
            return index(request)
    ##return from view form = FirstForm() the first encounter of the page
    return render(request, 'appone/form_page.html', {'form': form})

webdict/templates/appone/form_page.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"><meta charset="UTF-8">
    <title>UserPage</title>
</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
     <a class="navbar-brand" href="{% url 'index' %}">Home</a>
    <a class="nav-link" href="{% url 'appone:FormView' %}">Add word</a>
    </nav>
<h3>Add new keyword to dictionary:</h3>
<hr>
  <form method="POST">
    {{form.as_p}}
    {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Add to dictionary">
</form>
</div>
</body>
</html>

webdict/templates/appone/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <meta charset="UTF-8">
    <title>Homepage</title>
</head>
<body>
<div class="container">
     <nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'index' %}">Home</a>
    <a class="nav-link" href="{% url 'appone:FormView' %}">Add word</a>
         </nav>
    <br>
    <h1>List of added keywords:</h1>
    <hr>
    {% for i in words %}
    <li><strong>{{i.name}}</strong> = {{i.description}} added at {{i.created_at}}</li>
    {% endfor %}
    <hr>
    <form method="POST">
    {{form.as_p}}
    {% csrf_token %}
        <input type="submit" class="btn btn-primary" value="Delete Word">
<!--</form>-->
</div>
</body>
</html>